[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
turbine_q2_26_nft_marketplace = "GdpmNmSGvz9AkftRpjdCXKeRroQie68vzUufvZTyCy8V"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
