[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
turbine_q2_26_nft_marketplace = "3rkuu4wrct8cn9hd8fPzno8fW9bDKikhykAjwT8ASVdA"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
